[[main]]
  identifier = "about"
  name = "about"
  url = "/"
  weight = 1

[[main]]
  identifier = "posts"
  name = "blog"
  url = "posts"
  weight = 2

[[main]]
  identifier = "portfolio"
  name = "portfolio"
  url = "portfolio"
  weight = 2

[[main]]
  identifier = "iam"
  name = "i am"
  url = "iam"
  weight = 3