logoText = "Dani's Blog"
description = "The life (and blog) of Daniel E. Sandoval (Dani)"
custom_css = []
custom_js = []

themeOptions = ["dark", "light"]
notAllowedTypesInHome = ["contact", "talks", "about"]

# header
homeHeaderType = "text" # text, img, slide

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"

# whoami
myname = "Dani (d3sandoval)"
email = "daniel@desandoval.net"
whoami = "Product Designer"
useGravatar = false
location = "Cambridge, MA"
organization = "Pivotal Labs (VMware)"
link = "https://desandoval.net"

# sidebar
enableBio = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableToc = true
hideToc = false
enableTocSwitch = true
itemsPerCategory = 5

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment
enableComment = true
disqus_shortname = ""
commento = false

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = '你的appId'
  appKey = '你的appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = '说点什么吧...'
  visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # 来必力

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:daniel@desandoval.net"
  facebook = "https://facebook.com/d3sandoval"
  twitter = "http://twitter.com/d3sandoval"
  github = "https://github.com/d3sandoval"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = "https://medium.com/@d3sandoval"
  tumblr = ""
  linkedin = "https://linkedin.com/in/d3sandoval"
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  zhihu = ""
  gitlab = ""
  mastodon = ""

[donationOptions]
  enable = true
  alipay = "" 
  wechat = ""
  paypal = "danielericsandoval@gmail.com"
  patreon = ""