logoText = "Dani's Blog"
description = "The life (and blog) of Daniel E. Sandoval (Dani)"
custom_css = []
custom_js = []

# whoami
myname = "Dani (d3sandoval)"
email = "daniel@desandoval.net"
whoami = "Product Designer"
location = "Cambridge, MA"
organization = "Pivotal Labs (VMware)"
link = "https://desandoval.net"

[socialOptions]
  email = "mailto:daniel@desandoval.net"
  facebook = "https://facebook.com/d3sandoval"
  twitter = "http://twitter.com/d3sandoval"
  github = "https://github.com/d3sandoval"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = "https://medium.com/@d3sandoval"
  tumblr = ""
  linkedin = "https://linkedin.com/in/d3sandoval"
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  zhihu = ""
  gitlab = ""
  mastodon = ""
